# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    scan(workspace: "dangerTest.xcworkspace",
         scheme: "dangerTest",
         code_coverage: true,
         derived_data_path: "./Build",
         fail_build: false,
         devices: ["iPhone 11 Pro Max"],
         formatter: 'xcpretty-json-formatter',
         clean: true)

    command = "git add . && git commit -m \"Run crawler and update current data\""
    sh(command, log: true, error_callback: ->(result) { })
    push_to_git_remote


  end
end
