name: Swift

on:
  schedule:
     - cron: '0,10 1 * * 4'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      IS_GITHUB: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
