name: Swift

on: 
  pull_request:
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Tag Version'     
        required: true
        default: '1.1.0'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: ruby 2,7    
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Pod install
        run: bundle exec pod install --repo-update

       
      - name: Force select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
     
      - name: Fast
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'custom_lane'

      - name: brew install danger/tap/danger-swift
        run: brew install danger/tap/danger-swift


      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Danger ci
        run: danger-swift ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
