name: Swift

on: [push, workflow_dispatch]

jobs:
  checkout:
    runs-on: macos-latest
    timeout-minutes: 30
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

  bundle:
    runs-on: macos-latest
    needs: checkout
    timeout-minutes: 30
    
    steps:
      - name: Bundle install
        run: |
          bundle install
   

