name: Swift

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Pod install
        run: bundle exec pod install --repo-update

      - name: export
        run: export GITHUB_TOKEN=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
        
      - name: Force select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
     
      - name: brew install danger/tap/danger-swift
        run: brew install danger/tap/danger-swift

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Danger
        run: danger-swift pr https://github.com/gubookone/DangerTest/pull/1 --failOnErrors --no-publish-check


  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Gem install bundler
        run: gem install bundler

      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
